// src/utils/surahs-id.ts
export const surahs = [
    "Al-Fatihah – Pembukaan",
    "Al-Baqarah – Sapi Betina",
    "Ali Imran – Keluarga Imran",
    "An-Nisa – Wanita",
    "Al-Maidah – Hidangan",
    "Al-An'am – Binatang Ternak",
    "Al-A'raf – Tempat Tertinggi",
    "Al-Anfal – Rampasan Perang",
    "At-Taubah – Pengampunan",
    "Yunus – Nabi Yunus",
    "Hud – Nabi Hud",
    "Yusuf – Nabi Yusuf",
    "Ar-Ra'd – Guruh/Petir",
    "Ibrahim – Nabi Ibrahim",
    "Al-Hijr – Bukit Batu",
    "An-Nahl – Lebah",
    "Al-Isra – Perjalanan Malam",
    "Al-Kahf – Goa",
    "Maryam – Maryam",
    "Ta-Ha – Ta Ha",
    "Al-Anbiya – Para Nabi",
    "Al-Hajj – Haji",
    "Al-Mu’minun – Orang-Orang Mukmin",
    "An-Nur – Cahaya",
    "Al-Furqan – Pembeda",
    "Asy-Syu’ara – Para Penyair",
    "An-Naml – Semut",
    "Al-Qashash – Cerita",
    "Al-Ankabut – Laba-Laba",
    "Ar-Rum – Bangsa Romawi",
    "Luqman – Luqman",
    "As-Sajdah – Sujud",
    "Al-Ahzab – Golongan-Golongan yang Bersekutu",
    "Saba’ – Kaum Saba’",
    "Fatir – Pencipta",
    "Ya-Sin – Ya Sin",
    "As-Saffat – Barisan-Barisan",
    "Sad – Huruf Sad",
    "Az-Zumar – Rombongan",
    "Ghafir – Maha Pengampun",
    "Fussilat – Yang Dijelaskan",
    "Asy-Syura – Musyawarah",
    "Az-Zukhruf – Perhiasan Emas",
    "Ad-Dukhan – Asap",
    "Al-Jatsiyah – Yang Bertekuk Lutut",
    "Al-Ahqaf – Bukit-Bukit Pasir",
    "Muhammad – Nabi Muhammad",
    "Al-Fath – Kemenangan",
    "Al-Hujurat – Kamar-Kamar",
    "Qaf – Huruf Qaf",
    "Adz-Dzariyat – Angin yang Menerbangkan",
    "At-Tur – Bukit",
    "An-Najm – Bintang",
    "Al-Qamar – Bulan",
    "Ar-Rahman – Yang Maha Pemurah",
    "Al-Waqi’ah – Hari Kiamat",
    "Al-Hadid – Besi",
    "Al-Mujadilah – Wanita yang Mengajukan Gugatan",
    "Al-Hasyr – Pengusiran",
    "Al-Mumtahanah – Wanita yang Diuji",
    "As-Saff – Barisan",
    "Al-Jumu’ah – Hari Jumat",
    "Al-Munafiqun – Orang-Orang Munafik",
    "At-Taghabun – Hari Dinampakkan Kesalahan",
    "At-Talaq – Talak",
    "At-Tahrim – Pengharaman",
    "Al-Mulk – Kerajaan",
    "Al-Qalam – Pena",
    "Al-Haqqah – Hari Kiamat yang Pasti Terjadi",
    "Al-Ma’arij – Tempat-Tempat Naik",
    "Nuh – Nabi Nuh",
    "Al-Jinn – Jin",
    "Al-Muzzammil – Orang yang Berselimut",
    "Al-Muddassir – Orang yang Berselimut Pakaian",
    "Al-Qiyamah – Hari Kiamat",
    "Al-Insan – Manusia",
    "Al-Mursalat – Malaikat-Malaikat yang Diutus",
    "An-Naba – Berita Besar",
    "An-Nazi’at – Malaikat-Malaikat yang Mencabut",
    "‘Abasa – Ia Bermuka Masam",
    "At-Takwir – Menggulung",
    "Al-Infitar – Terbelah",
    "Al-Muthaffifin – Orang-Orang yang Curang",
    "Al-Insyiqaq – Terbelah",
    "Al-Buruj – Gugusan Bintang",
    "At-Tariq – Bintang yang Menyinar",
    "Al-A’la – Yang Maha Tinggi",
    "Al-Ghasyiyah – Hari Kiamat yang Menggelisahkan",
    "Al-Fajr – Fajar",
    "Al-Balad – Negeri",
    "Asy-Syams – Matahari",
    "Al-Lail – Malam",
    "Adh-Dhuha – Waktu Dhuha",
    "Asy-Syarh – Kelapangan",
    "At-Tin – Buah Tin",
    "Al-‘Alaq – Segumpal Darah",
    "Al-Qadr – Kemuliaan",
    "Al-Bayyinah – Bukti yang Nyata",
    "Az-Zalzalah – Kegoncangan",
    "Al-‘Adiyat – Kuda Perang yang Berlari Kencang",
    "Al-Qari’ah – Hari Kiamat",
    "At-Takatsur – Berlomba-lomba Memperbanyak",
    "Al-‘Asr – Waktu",
    "Al-Humazah – Pengumpat",
    "Al-Fil – Gajah",
    "Quraisy – Kaum Quraisy",
    "Al-Ma’un – Barang-Barang yang Berguna",
    "Al-Kautsar – Nikmat yang Banyak",
    "Al-Kafirun – Orang-Orang Kafir",
    "An-Nasr – Pertolongan",
    "Al-Lahab (Al-Masad) – Gejolak Api",
    "Al-Ikhlas – Ikhlas",
    "Al-Falaq – Waktu Subuh",
    "An-Nas – Manusia"
];
  